const translations = {
    en: {
        translation: {
            "language-selector": "Select Language:",
            "start_label": "Start Location:",
            "end_label": "End Location:",
            "algorithm_label": "Algorithm:",
            "find_route_btn": "Find Route",
            "select_a_start_label": "Select a start location",
            "select_an_end_label": "Select an end location",
            "algorithm_select_label": "Choose an algorithm",
            "algorithm_bfs_label": "BFS",
            "algorithm_dfs_label": "DFS",
            "algorithm_dik_label": "Dijkstra's Algorithm",
            "god_mode_enable_btn": "🛠️ Enable God Mode",
            "god_mode_disable_btn": "🔴 Disable God Mode",
            "export_btn": "💾 Save & Download Edited Network"
        }
    },
    zh: {
        translation: {
            "language-selector": "選擇語言：",
            "start_label": "起始位置：",
            "end_label": "終點位置：",
            "algorithm_label": "演算法：",
            "find_route_btn": "尋找路線",
            "select_a_start_label": "選擇一個起始位置",
            "select_an_end_label": "選擇一個終點位置",
            "algorithm_select_label": "選擇一個演算法：",
            "algorithm_bfs_label": "廣度優先走訪",
            "algorithm_dfs_label": "深度優先走訪",
            "algorithm_dik_label": "戴克斯特拉演算法",
            "god_mode_enable_btn": "🛠️ 開啟上帝模式",
            "god_mode_disable_btn": "🔴 關閉上帝模式",
            "export_btn": "💾 儲存並下載修改後的路網"
        }
    }
};
const buildingTranslations = {
  "元氣早餐": { "zh": "元氣早餐", "en": "Genki Breakfast" },
  "全家便利商店-民雄神農店": { "zh": "全家便利商店-民雄神農店", "en": "FamilyMart - Minxiong Shennong Store" },
  "7-ELEVEN 中正大學門市": { "zh": "7-ELEVEN 中正大學門市", "en": "7-ELEVEN - CCU Store" },
  "全家便利商店-共教店": { "zh": "全家便利商店-共教店", "en": "FamilyMart - Joint Classroom Store" },
  "A-bao": { "zh": "A-bao", "en": "A-bao" },
  "三米藍": { "zh": "三米藍", "en": "San Milan" },
  "即食樂": { "zh": "即食樂", "en": "Ji Shi Le" },
  "8鍋時尚新穎小火鍋": { "zh": "8鍋時尚新穎小火鍋", "en": "8 Pot" },
  "i嘎嗶複合式餐廳": { "zh": "i嘎嗶複合式餐廳", "en": "i-Gabi Fusion Restaurant" },
  "全家便利商店-活動中心店": { "zh": "全家便利商店-活動中心店", "en": "FamilyMart - Activity Center Store" },
  "品味香快炒": { "zh": "品味香快炒", "en": "Pin Wei Xiang Stir-fry" },
  "花漾廚房": { "zh": "花漾廚房", "en": "Floral Kitchen" },
  "7-ELEVEN 溫莎門市": { "zh": "7-ELEVEN 溫莎門市", "en": "7-ELEVEN - Windsor Store" },
  "萊爾富-民雄神農店": { "zh": "萊爾富-民雄神農店", "en": "Hi-Life - Minxiong Shennong Store" },
  "神農美食坊": { "zh": "神農美食坊", "en": "Shennong Food Court" },
  "中正快炒": { "zh": "中正快炒", "en": "Zhongzheng Stir-fry" },
  "米六里": { "zh": "米六里", "en": "Mi Liu Li" },
  "ㄎㄎ韓食": { "zh": "ㄎㄎ韓食", "en": "Ke Ke Korean Food" },
  "薩克廚房": { "zh": "薩克廚房", "en": "Zac's Kitchen" },
  "鮮茶道": { "zh": "鮮茶道", "en": "Presotea" },
  "地中海美食": { "zh": "地中海美食", "en": "Mediterranean Food" },
  "Tea's原味": { "zh": "Tea's原味", "en": "Tea's" },
  "晨間廚房": { "zh": "晨間廚房", "en": "Morning Kitchen" },
  "全家便利商店-民雄旺萊店": { "zh": "全家便利商店-民雄旺萊店", "en": "FamilyMart - Minxiong Wanglai Store" },
  "123活力早餐屋": { "zh": "123活力早餐屋", "en": "123 Vitality Breakfast" },
  "瘋beef": { "zh": "瘋beef", "en": "Crazy Beef" },
  "麥香堡早午餐": { "zh": "麥香堡早午餐", "en": "Mai Xiang Bao Brunch" },
  "順傑電動車": { "zh": "順傑電動車", "en": "Shun Jie Electric Vehicles" },
  "Yes 厚切雞排": { "zh": "Yes 厚切雞排", "en": "Yes Thick-Cut Chicken Filet" },
  "伊卓島": { "zh": "伊卓島", "en": "Yizhuo Island" },
  "六妹食堂": { "zh": "六妹食堂", "en": "Liu Mei Diner" },
  "侯記中式早餐": { "zh": "侯記中式早餐", "en": "Hou's Chinese Breakfast" },
  "豪記滷味-升學路": { "zh": "豪記滷味-升學路", "en": "Hao's Braised Food - Shengxue Road" },
  "財哥鹹酥雞": { "zh": "財哥鹹酥雞", "en": "Brother Cai's Salted Crispy Chicken" },
  "丼飽處": { "zh": "丼飽處", "en": "Donburi Eatery" },
  "味芳早餐": { "zh": "味芳早餐", "en": "Wei Fang Breakfast" },
  "泰麻吉": { "zh": "泰麻吉", "en": "Thai Machi" },
  "全方味便當、咖哩飯、炒泡麵": { "zh": "全方味便當、咖哩飯、炒泡麵", "en": "Quan Fang Wei Bento, Curry, Fried Instant Noodles" },
  "阿梅簡餐便當": { "zh": "阿梅簡餐便當", "en": "A-Mei Bento & Set Meals" },
  "二口食堂": { "zh": "二口食堂", "en": "Er Kou Diner" },
  "a咖牛排": { "zh": "a咖牛排", "en": "A-Class Steak" },
  "果然製物所": { "zh": "果然製物所", "en": "Guoran Studio" },
  "蝦皮店到店": { "zh": "蝦皮店到店", "en": "Shopee Store-to-Store" },
  "Simple Fit 簡單瘦健康餐": { "zh": "Simple Fit 簡單瘦健康餐", "en": "Simple Fit Healthy Meals" },
  "湖畔咖啡": { "zh": "湖畔咖啡", "en": "Lakeside Coffee" },
  "艾絲": { "zh": "艾絲", "en": "Ice / Aisi" },
  "行政大樓": { "zh": "行政大樓", "en": "Administration Building" },
  "社會科學院": { "zh": "社會科學院", "en": "College of Social Sciences" },
  "共同教室大樓": { "zh": "共同教室大樓", "en": "Joint Classroom Building" },
  "工學院": { "zh": "工學院", "en": "College of Engineering" },
  "禮堂": { "zh": "禮堂", "en": "Auditorium" },
  "學生活動中心": { "zh": "學生活動中心", "en": "Student Activity Center" },
  "工學院二館": { "zh": "工學院二館", "en": "College of Engineering Building 2" },
  "法學院": { "zh": "法學院", "en": "College of Law" },
  "教育學院": { "zh": "教育學院", "en": "College of Education" },
  "教育學院二館": { "zh": "教育學院二館", "en": "College of Education Building 2" },
  "理學院": { "zh": "理學院", "en": "College of Science" },
  "理學院二館": { "zh": "理學院二館", "en": "College of Science Building 2" },
  "中正大學體育館": { "zh": "中正大學體育館", "en": "CCU Gymnasium" },
  "圖書資訊大樓": { "zh": "圖書資訊大樓", "en": "Library and Information Building" },
  "致遠樓": { "zh": "致遠樓", "en": "Zhiyuan Building" },
  "生活商圈": { "zh": "生活商圈", "en": "Life Commercial District" },
  "員工學生福利社": { "zh": "員工學生福利社", "en": "Staff and Student Cooperative" },
  "大學部宿舍E棟": { "zh": "大學部宿舍E棟", "en": "Undergraduate Dormitory E" },
  "大學部宿舍C棟": { "zh": "大學部宿舍C棟", "en": "Undergraduate Dormitory C" },
  "大學部宿舍D棟": { "zh": "大學部宿舍D棟", "en": "Undergraduate Dormitory D" },
  "大學部宿舍B棟": { "zh": "大學部宿舍B棟", "en": "Undergraduate Dormitory B" },
  "大學部宿舍A棟": { "zh": "大學部宿舍A棟", "en": "Undergraduate Dormitory A" },
  "研究生宿舍A棟": { "zh": "研究生宿舍A棟", "en": "Graduate Dormitory A" },
  "研究生宿舍B棟": { "zh": "研究生宿舍B棟", "en": "Graduate Dormitory B" },
  "研究生宿舍E棟": { "zh": "研究生宿舍E棟", "en": "Graduate Dormitory E" },
  "研究生宿舍C棟": { "zh": "研究生宿舍C棟", "en": "Graduate Dormitory C" },
  "研究生宿舍D棟": { "zh": "研究生宿舍D棟", "en": "Graduate Dormitory D" },
  "實習工廠": { "zh": "實習工廠", "en": "Practice Factory" },
  "陶潛": { "zh": "陶潛", "en": "Tao Qian" },
  "鳳凰軒": { "zh": "鳳凰軒", "en": "Fenghuang Pavilion" },
  "中正大學變電所(C/S)": { "zh": "中正大學變電所(C/S)", "en": "CCU Substation (C/S)" },
  "創新大樓": { "zh": "創新大樓", "en": "Innovation Building" },
  "現代首席": { "zh": "現代首席", "en": "Modern Chief" },
  "正心學院": { "zh": "正心學院", "en": "Zhengxin Academy" },
  "康乃爾學院": { "zh": "康乃爾學院", "en": "Cornell Academy" },
  "京采": { "zh": "京采", "en": "Jing Cai" },
  "墨香苑": { "zh": "墨香苑", "en": "Moxiang Court" },
  "凱格鹿三期": { "zh": "凱格鹿三期", "en": "Kaigelu Phase 3" },
  "集智苑": { "zh": "集智苑", "en": "Jizhi Court" },
  "陶居": { "zh": "陶居", "en": "Tao Ju" },
  "木菊苑": { "zh": "木菊苑", "en": "Muju Court" },
  "書香門第": { "zh": "書香門第", "en": "Scholarly Family" },
  "維多利亞學苑": { "zh": "維多利亞學苑", "en": "Victoria Academy" },
  "哈佛學苑": { "zh": "哈佛學苑", "en": "Harvard Academy" },
  "凱格鹿二期": { "zh": "凱格鹿二期", "en": "Kaigelu Phase 2" },
  "牛津學苑": { "zh": "牛津學苑", "en": "Oxford Academy" },
  "康乃爾學苑": { "zh": "康乃爾學苑", "en": "Cornell Academy" },
  "苗圃": { "zh": "苗圃", "en": "Nursery" },
  "動物實驗室": { "zh": "動物實驗室", "en": "Animal Laboratory" },
  "食凡捲餅": { "zh": "食凡捲餅", "en": "Shi Fan Burrito" },
  "理學院-地震博物館": { "zh": "理學院-地震博物館", "en": "College of Science - Earthquake Museum" },
  "理學院-物理館": { "zh": "理學院-物理館", "en": "College of Science - Physics Building" },
  "金桔學苑": { "zh": "金桔學苑", "en": "Kumquat Academy" },
  "凱格鹿旗艦會館": { "zh": "凱格鹿旗艦會館", "en": "Kaigelu Flagship Hall" },
  "靈糧堂": { "zh": "靈糧堂", "en": "Bread of Life Christian Church" },
  "深白舍": { "zh": "深白舍", "en": "Pure White House" },
  "橙舍": { "zh": "橙舍", "en": "Orange House" },
  "三豐學苑": { "zh": "三豐學苑", "en": "Sanfeng Academy" },
  "三豐學苑(二期)": { "zh": "三豐學苑(二期)", "en": "Sanfeng Academy (Phase 2)" },
  "柏克萊": { "zh": "柏克萊", "en": "Berkeley" },
  "彬彬": { "zh": "彬彬", "en": "Bin Bin" },
  "夏都": { "zh": "夏都", "en": "Chateau" },
  "管理學院二館": { "zh": "管理學院二館", "en": "College of Management Building 2" },
  "節能宿舍熱水設施": { "zh": "節能宿舍熱水設施", "en": "Energy-Saving Dormitory Hot Water Facility" },
  "三興村社區活動中心": { "zh": "三興村社區活動中心", "en": "Sanxing Village Community Activity Center" },
  "中正大學環安中心": { "zh": "中正大學環安中心", "en": "CCU Environmental Health and Safety Center" },
  "文學院": { "zh": "文學院", "en": "College of Humanities" },
  "三興國小": { "zh": "三興國小", "en": "Sanxing Elementary School" },
  "納米運動休閒園區": { "zh": "納米運動休閒園區", "en": "Nami Sports and Recreation Park" },
  "中正駕訓班": { "zh": "中正駕訓班", "en": "Zhongzheng Driving School" },
  "登林學苑": { "zh": "登林學苑", "en": "Denglin Academy" },
  "鼎泰": { "zh": "鼎泰", "en": "Dingtai" },
  "紫荊書苑": { "zh": "紫荊書苑", "en": "Zijing Academy" },
  "牛筋伯爵": { "zh": "牛筋伯爵", "en": "Earl Tendon" },
  "中正大學大門機車停車場": { "zh": "中正大學大門機車停車場", "en": "CCU Main Gate Scooter Parking Lot" },
  "大學部宿舍機車停車場": { "zh": "大學部宿舍機車停車場", "en": "Undergraduate Dormitory Scooter Parking Lot" },
  "匯幸福二期": { "zh": "匯幸福二期", "en": "Hui Xingfu Phase 2" },
  "學生會館": { "zh": "學生會館", "en": "Student Hostel" },
  "木菊苑二期": { "zh": "木菊苑二期", "en": "Muju Court Phase 2" },
  "天晴": { "zh": "天晴", "en": "Sunny" },
  "淡如菊": { "zh": "淡如菊", "en": "Danruju" },
  "21金小火鍋": { "zh": "21金小火鍋", "en": "21 Gold Hot Pot" },
  "Just Eat Brunch": { "zh": "Just Eat Brunch", "en": "Just Eat Brunch" },
  "布格早午餐": { "zh": "布格早午餐", "en": "Buge Brunch" },
  "博多屋台拉麵": { "zh": "博多屋台拉麵", "en": "Hakata Yatai Ramen" },
  "夏豔鳳翔會館": { "zh": "夏豔鳳翔會館", "en": "Xiayan Fengxiang Hall" },
  "劍橋世紀": { "zh": "劍橋世紀", "en": "Cambridge Century" },
  "三興村陳厝寮-大樹下簡餐便當": { "zh": "三興村陳厝寮-大樹下簡餐便當", "en": "Sanxing Village Chencuoliao - Dashuxia Bento" },
  "心遠居": { "zh": "心遠居", "en": "Xinyuan Ju" },
  "琪琪健康舖": { "zh": "琪琪健康舖", "en": "Kiki's Healthy Shop" },
  "阿姨早餐": { "zh": "阿姨早餐", "en": "Auntie's Breakfast" },
  "三興村陳厝寮-轉角早餐店": { "zh": "三興村陳厝寮-轉角早餐店", "en": "Sanxing Village Chencuoliao - Corner Breakfast" },
  "大四喜牛肉麵": { "zh": "大四喜牛肉麵", "en": "Da Si Xi Beef Noodle" },
  "諾貝爾學院": { "zh": "諾貝爾學院", "en": "Nobel Academy" },
  "常春藤學院": { "zh": "常春藤學院", "en": "Ivy Academy" },
  "凱格鹿九期": { "zh": "凱格鹿九期", "en": "Kaigelu Phase 9" },
  "享住I": { "zh": "享住I", "en": "Xiangzhu I" },
  "凱格鹿八期": { "zh": "凱格鹿八期", "en": "Kaigelu Phase 8" },
  "凱格鹿一期": { "zh": "凱格鹿一期", "en": "Kaigelu Phase 1" },
  "民雄鄉召會二會所(學生中心)": { "zh": "民雄鄉召會二會所(學生中心)", "en": "Minxiong Township Church Hall 2 (Student Center)" },
  "梓園": { "zh": "梓園", "en": "Zi Yuan" },
  "歐風學墅": { "zh": "歐風學墅", "en": "European Style Academy" },
  "鵬莊": { "zh": "鵬莊", "en": "Peng Zhuang" },
  "米蘭": { "zh": "米蘭", "en": "Milan" },
  "柏睿學院": { "zh": "柏睿學院", "en": "Borui Academy" },
  "康莊": { "zh": "康莊", "en": "Kang Zhuang" },
  "菁華學苑": { "zh": "菁華學苑", "en": "Jinghua Academy" },
  "鼎冠學苑": { "zh": "鼎冠學苑", "en": "Dingguan Academy" },
  "唯心之旅": { "zh": "唯心之旅", "en": "Journey of Idealism" },
  "三興會館民宿": { "zh": "三興會館民宿", "en": "Sanxing Hall B&B" },
  "凱媽的家1館": { "zh": "凱媽的家1館", "en": "Mama Kai's House Pavilion 1" },
  "中正會館": { "zh": "中正會館", "en": "Zhongzheng Hall" },
  "蔬香是家": { "zh": "蔬香是家", "en": "Shuxiang Shijia" },
  "中正美學": { "zh": "中正美學", "en": "Zhongzheng Aesthetics" },
  "博士學苑": { "zh": "博士學苑", "en": "Doctor Academy" },
  "巴豆夭百元美味鍋物": { "zh": "巴豆夭百元美味鍋物", "en": "Badouyao 100-Yuan Delicious Hot Pot" },
  "光明雅舍": { "zh": "光明雅舍", "en": "Guangming Yashe" },
  "早叄早午餐": { "zh": "早叄早午餐", "en": "Zao San Brunch" },
  "蔬芙": { "zh": "蔬芙", "en": "Shu Fu" },
  "八方雲集": { "zh": "八方雲集", "en": "Bafang Dumpling" },
  "阿基鍋燒麵": { "zh": "阿基鍋燒麵", "en": "A-Ji Nabeyaki Noodles" },
  "光陽機車": { "zh": "光陽機車", "en": "KYMCO" },
  "早餐好樂": { "zh": "早餐好樂", "en": "How The Breakfast" },
  "紘翔車業": { "zh": "紘翔車業", "en": "Hongxiang Motor" },
  "中正大學-廣場公園停車場": { "zh": "中正大學-廣場公園停車場一", "en": "CCU - Plaza Park Parking Lot 1" },
  "中正大學-廣場公園停車場": { "zh": "中正大學-廣場公園停車場二", "en": "CCU - Plaza Park Parking Lot 2" },
  "嘉義富野渡假酒店": { "zh": "嘉義富野渡假酒店", "en": "Hoya Resort Hotel Chiayi" },
  "YAMAHA-中正車坊": { "zh": "YAMAHA-中正車坊", "en": "YAMAHA - Zhongzheng Motorcycle Shop" },
  "中正偉文": { "zh": "中正偉文", "en": "Zhongzheng Weiwen" },
  "百田中西式早午餐": { "zh": "百田中西式早午餐", "en": "Baitian Chinese & Western Brunch" },
  "美廉社民雄裕農店": { "zh": "美廉社民雄裕農店", "en": "Simple Mart Minxiong Yunong Store" },
  "明發影印行": { "zh": "明發影印行", "en": "Mingfa Copy Shop" },
  "花圓巧芋": { "zh": "花圓巧芋", "en": "Hua Yuan Qiao Yu" },
  "高點網路學院": { "zh": "高點網路學院", "en": "Knowledge Master Network Academy" },
  "咖啡王國": { "zh": "咖啡王國", "en": "Coffee Kingdom" },
  "小樹苗電腦": { "zh": "小樹苗電腦", "en": "Little Sapling Computer" },
  "槍與玫瑰": { "zh": "槍與玫瑰", "en": "Guns N' Roses" },
  "橙堡早午餐": { "zh": "橙堡早午餐", "en": "Cheng Bao Brunch" },
  "韓湯匙 無人拉麵": { "zh": "韓湯匙 無人拉麵", "en": "Han Spoon Unmanned Ramen" },
  "小栗鼠cafe": { "zh": "小栗鼠cafe", "en": "Chipmunk Cafe" },
  "溫家冷滷味": { "zh": "溫家冷滷味", "en": "Wen's Cold Braised Food" },
  "月亮與貓｜貓貓甜點店": { "zh": "月亮與貓｜貓貓甜點店", "en": "Moon & Cat | Cat Dessert Shop" },
  "茶湯會 民雄神農店": { "zh": "茶湯會 民雄神農店", "en": "TP TEA Minxiong Shennong Store" },
  "豪緯麵食館": { "zh": "豪緯麵食館", "en": "Haowei Noodle Restaurant" },
  "仙草奶酪": { "zh": "仙草奶酪", "en": "Grass Jelly Panna Cotta" },
  "古早味炒麵（脆皮臭豆腐）": { "zh": "古早味炒麵（脆皮臭豆腐）", "en": "Traditional Fried Noodles (Crispy Stinky Tofu)" },
  "鍋序": { "zh": "鍋序", "en": "Guo Xu" },
  "蘭姐手工水餃": { "zh": "蘭姐手工水餃", "en": "Sister Lan's Handmade Dumplings" },
  "紅樓極麵": { "zh": "紅樓極麵", "en": "Red Chamber Ultimate Noodles" },
  "東方美早午餐": { "zh": "東方美早午餐", "en": "Dongfang Mei Brunch" },
  "隱客廳": { "zh": "隱客廳", "en": "Hidden Living Room" },
  "一番食堂": { "zh": "一番食堂", "en": "Ichiban Diner" },
  "洵香麻辣燙": { "zh": "洵香麻辣燙", "en": "Xun Xiang Malatang" },
  "翅炸鍋": { "zh": "翅炸鍋", "en": "Chi Zha Guo" },
  "富成屋拉麵": { "zh": "富成屋拉麵", "en": "Fuchenwu Ramen" },
  "豐正食堂": { "zh": "豐正食堂", "en": "Fengzheng Diner" },
  "傻師傅神農店": { "zh": "傻師傅神農店", "en": "Sha Shifu Shennong Store" },
  "烘培工房": { "zh": "烘培工房", "en": "Baking Workshop" },
  "嘉農小館": { "zh": "嘉農小館", "en": "Jianong Diner" },
  "榕樹下": { "zh": "榕樹下", "en": "Under the Banyan Tree" },
  "中正海南雞飯": { "zh": "中正海南雞飯", "en": "Zhongzheng Hainanese Chicken Rice" },
  "鹿初Brunch": { "zh": "鹿初Brunch", "en": "Lu Chu Brunch" },
  "洪媽媽泰式簡餐": { "zh": "洪媽媽泰式簡餐", "en": "Mother Hong's Thai Set Meals" },
  "有go滷乾式炒滷味": { "zh": "有go滷乾式炒滷味", "en": "You Go Lu Dry Braised Food" },
  "越式炒泡麵、河粉": { "zh": "越式炒泡麵、河粉", "en": "Vietnamese Fried Instant Noodles & Pho" },
  "王仔滷味": { "zh": "王仔滷味", "en": "Wang's Braised Food" },
  "愛恨椒雞": { "zh": "愛恨椒雞", "en": "Ai Hen Jiao Ji" },
  "農閒時刻的粥": { "zh": "農閒時刻的粥", "en": "Nongxian Shike Congee" },
  "十畝田滷味": { "zh": "十畝田滷味", "en": "Shimutian Braised Food" },
  "巧味果汁": { "zh": "巧味果汁", "en": "Qiao Wei Juice" },
  "阿湯哥脆皮湯包": { "zh": "阿湯哥脆皮湯包", "en": "Tom's Crispy Soup Dumplings" },
  "早安山丘": { "zh": "早安山丘", "en": "Morning Hill" },
  "大榮數位輸出影印行": { "zh": "大榮數位輸出影印行", "en": "Darong Digital Copy Shop" },
  "渝香园簡餐": { "zh": "渝香园簡餐", "en": "Yuxiangyuan Set Meals" },
  "鴻昇數位輸出影印中心": { "zh": "鴻昇數位輸出影印中心", "en": "Hongsheng Digital Copy Center" },
  "Nice Nine 雙醬咖哩": { "zh": "Nice Nine 雙醬咖哩", "en": "Nice Nine Double Sauce Curry" },
  "豪豪吃早餐": { "zh": "豪豪吃早餐", "en": "Hao Hao Eats Breakfast" },
  "關東煮炒麵炒米粉": { "zh": "關東煮炒麵炒米粉", "en": "Oden, Fried Noodles, Fried Rice Noodles" },
  "豪記滷味-神農路": { "zh": "豪記滷味-神農路", "en": "Hao's Braised Food - Shennong Road" },
  "中正大學員工子女非營利幼兒園": { "zh": "中正大學員工子女非營利幼兒園", "en": "CCU Employee Children's Non-Profit Kindergarten" },
  "東側門汽機車停車場": { "zh": "東側門汽機車停車場", "en": "East Gate Car & Scooter Parking Lot" },
  "全家便利商店-學人宿舍店": { "zh": "全家便利商店-學人宿舍店", "en": "FamilyMart - Scholar Dormitory Store" },
  "管理學院": { "zh": "管理學院", "en": "College of Management" },
  "中正大學訪客停車場": { "zh": "中正大學訪客停車場", "en": "CCU Visitor Parking Lot" },
  "中正大學公車站": { "zh": "中正大學公車站", "en": "CCU Bus Station" },
  "麗文-中正大學店": { "zh": "麗文-中正大學店", "en": "Liwen - CCU Store" },
  "露易莎-中正大學店": { "zh": "露易莎-中正大學店", "en": "Louisa Coffee - CCU Store" },
  "學生餐廳": { "zh": "學生餐廳", "en": "Student Cafeteria" },
  "中正大學郵局": { "zh": "中正大學郵局", "en": "CCU Post Office" },
  "中正大學影印店": { "zh": "中正大學影印店", "en": "CCU Copy Shop" },
  "中正大學網球場": { "zh": "中正大學網球場", "en": "CCU Tennis Court" },
  "中正大學田徑場": { "zh": "中正大學田徑場", "en": "CCU Track and Field" },
  "中正大學籃球場": { "zh": "中正大學籃球場", "en": "CCU Basketball Court" },
  "中正大學排球場": { "zh": "中正大學排球場", "en": "CCU Volleyball Court" },
  "中正大學棒球場": { "zh": "中正大學棒球場", "en": "CCU Baseball Field" },
  "中正大學景觀花園": { "zh": "中正大學景觀花園", "en": "CCU Landscape Garden" },
  "中正大學射箭場": { "zh": "中正大學射箭場", "en": "CCU Archery Range" },
  "中正大學壘球場": { "zh": "中正大學壘球場", "en": "CCU Softball Field" },
  "中正大學足球場": { "zh": "中正大學足球場", "en": "CCU Football Field" },
  "中正大學高爾夫球練習場": { "zh": "中正大學高爾夫球練習場", "en": "CCU Golf Practice Range" },
  "中正大學室外游泳池": { "zh": "中正大學室外游泳池", "en": "CCU Outdoor Swimming Pool" },
  "研究生機車停車場": { "zh": "研究生機車停車場", "en": "Graduate Dormitory Scooter Parking Lot" },
  "中正大學室內綜合球場": { "zh": "中正大學室內綜合球場", "en": "CCU Indoor Multipurpose Court" },
  "中正大學攀岩場": { "zh": "中正大學攀岩場", "en": "CCU Climbing Wall" },
  "中正大學室內游泳池": { "zh": "中正大學室內游泳池", "en": "CCU Indoor Swimming Pool" },
  "旺記": { "zh": "旺記", "en": "Wang Ji" },
  "楊家豆漿": { "zh": "楊家豆漿", "en": "Yang's Soy Milk" },
  "不吃不可鹽水雞": { "zh": "不吃不可鹽水雞", "en": "Must Eat Salted Water Chicken" },
  "德州撲克競技協會": { "zh": "德州撲克競技協會", "en": "Texas Hold'em Poker Association" },
};
function applyTranslations(lang) {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang].translation[key]) {
            el.textContent = translations[lang].translation[key];
        }
    });
}

// React to the selector change
const selector = document.getElementById('language-selector');
selector.addEventListener('change', (e) => {
    const lang = e.target.value;
    applyTranslations(lang);
    localStorage.setItem('preferredLang', lang);
});

// Initialization
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('preferredLang') || 'zh';
    selector.value = savedLang;
    applyTranslations(savedLang);
});

function updateDropdownLanguage(currentLang) {
  const startSelect = document.getElementById("start");
  const endSelect = document.getElementById("end");

  if (!startSelect || !endSelect) return;

  // 更新下拉選單的選項 (只處理真正的大樓)
  function translateOptions(selectElement) {
    Array.from(selectElement.options).forEach(option => {
      // 1. 預設的防呆選項 (value 是空的) 已經有 data-i18n 會處理，這裡直接跳過！
      if (option.value === "") {
        return;
      }
      
      // 2. 處理真實的大樓選項
      const translation = buildingTranslations[option.value];
      if (translation && translation[currentLang]) {
        // 如果字典裡有這個大樓的翻譯，就換成該語言的顯示文字
        option.text = translation[currentLang];
      } else {
        // 找不到翻譯就保留原名
        option.text = option.value; 
      }
    });
  }

  // 執行翻譯 (不用再傳遞 "start" 或 "end" 了)
  translateOptions(startSelect);
  translateOptions(endSelect);
}