const buildingTranslations = {
  "元氣早餐": { "zh": "元氣早餐", "en": "Yuan Qi Breakfast" },
  "全家便利商店-民雄神農店": { "zh": "全家便利商店-民雄神農店", "en": "FamilyMart - Minxiong Shennong Store" },
  "7-ELEVEN 中正大學門市": { "zh": "7-ELEVEN 中正大學門市", "en": "7-ELEVEN - CCU Store" },
  "全家便利商店-共教店": { "zh": "全家便利商店-共教店", "en": "FamilyMart - Common Classroom Store" },
  "A-bao": { "zh": "A-bao", "en": "A-bao" },
  "三米藍": { "zh": "三米藍", "en": "San Milan" },
  "即食樂": { "zh": "即食樂", "en": "Ji Shi Le" },
  "8鍋時尚新穎小火鍋": { "zh": "8鍋時尚新穎小火鍋", "en": "8 Pot Hot Pot" },
  "i嘎嗶複合式餐廳": { "zh": "i嘎嗶複合式餐廳", "en": "i-Coffee Fusion Restaurant" },
  "全家便利商店-活動中心店": { "zh": "全家便利商店-活動中心店", "en": "FamilyMart - Activity Center Store" },
  "品味香快炒": { "zh": "品味香快炒", "en": "Pin Wei Xiang Stir-fry" },
  "花漾廚房": { "zh": "花漾廚房", "en": "Hua Yang Kitchen" },
  "7-ELEVEN 溫莎門市": { "zh": "7-ELEVEN 溫莎門市", "en": "7-ELEVEN - Windsor Store" },
  "萊爾富-民雄神農店": { "zh": "萊爾富-民雄神農店", "en": "Hi-Life - Minxiong Shennong Store" },
  "神農美食坊": { "zh": "神農美食坊", "en": "Shennong Food Court" },
  "中正快炒": { "zh": "中正快炒", "en": "Zhongzheng Stir-fry" },
  "米六里": { "zh": "米六里", "en": "Mi Liu Li" },
  "ㄎㄎ韓食": { "zh": "ㄎㄎ韓食", "en": "KK Korean Food" },
  "薩克廚房": { "zh": "薩克廚房", "en": "Sack Kitchen" },
  "鮮茶道": { "zh": "鮮茶道", "en": "Presotea" },
  "地中海美食": { "zh": "地中海美食", "en": "Mediterranean Food" },
  "Tea's原味": { "zh": "Tea's原味", "en": "Tea's Original" },
  "晨間廚房": { "zh": "晨間廚房", "en": "Morning Kitchen" },
  "全家便利商店-民雄旺萊店": { "zh": "全家便利商店-民雄旺萊店", "en": "FamilyMart - Minxiong Wanglai Store" },
  "誠石 石頭火鍋": { "zh": "誠石 石頭火鍋", "en": "Chengshi Stone Hot Pot" },
  "123活力早餐屋": { "zh": "123活力早餐屋", "en": "123 Vitality Breakfast" },
  "中正比奇寶": { "zh": "中正比奇寶", "en": "Zhongzheng Bi Qi Bao" },
  "瘋beef": { "zh": "瘋beef", "en": "Crazy Beef" },
  "麥香堡早午餐": { "zh": "麥香堡早午餐", "en": "Mai Xiang Bao Brunch" },
  "順傑電動車": { "zh": "順傑電動車", "en": "Shunjie Electric Vehicles" },
  "Yes 厚切雞排": { "zh": "Yes 厚切雞排", "en": "Yes Thick-Cut Chicken Filet" },
  "伊卓島": { "zh": "伊卓島", "en": "Yizhuo Island" },
  "六妹食堂": { "zh": "六妹食堂", "en": "Liu Mei Eatery" },
  "另類創意現炒美食": { "zh": "另類創意現炒美食", "en": "Alternative Creative Stir-fry Food" },
  "侯記中式早餐": { "zh": "侯記中式早餐", "en": "Hou's Chinese Breakfast" },
  "豪記滷味-升學路": { "zh": "豪記滷味-升學路", "en": "Haoji Luwei - Shengxue Road" },
  "財哥鹹酥雞": { "zh": "財哥鹹酥雞", "en": "Brother Cai's Salted Crispy Chicken" },
  "丼飽處": { "zh": "丼飽處", "en": "Dong Bao Chu" },
  "味芳早餐": { "zh": "味芳早餐", "en": "Weifang Breakfast" },
  "泰麻吉": { "zh": "泰麻吉", "en": "Thai Machi" },
  "好味軒廚房": { "zh": "好味軒廚房", "en": "Haoweixuan Kitchen" },
  "全方味便當、咖哩飯、炒泡麵": { "zh": "全方味便當、咖哩飯、炒泡麵", "en": "Quanfangwei Bento, Curry Rice & Fried Instant Noodles" },
  "阿梅簡餐便當": { "zh": "阿梅簡餐便當", "en": "A-Mei Fast Food & Bento" },
  "二口食堂": { "zh": "二口食堂", "en": "Er Kou Eatery" },
  "a咖牛排": { "zh": "a咖牛排", "en": "A-Class Steak" },
  "果然製物所": { "zh": "果然製物所", "en": "Guo Ran Studio" },
  "蝦皮店到店": { "zh": "蝦皮店到店", "en": "Shopee Xpress" },
  "Simple Fit 簡單瘦健康餐": { "zh": "Simple Fit 簡單瘦健康餐", "en": "Simple Fit Healthy Diet" },
  "湖畔咖啡": { "zh": "湖畔咖啡", "en": "Lakeside Coffee" },
  "艾絲": { "zh": "艾絲", "en": "Ai Si" },
  "行政大樓": { "zh": "行政大樓", "en": "Administration Building" },
  "社會科學院": { "zh": "社會科學院", "en": "College of Social Sciences" },
  "共同教室大樓": { "zh": "共同教室大樓", "en": "Common Classroom Building" },
  "工學院": { "zh": "工學院", "en": "College of Engineering" },
  "禮堂": { "zh": "禮堂", "en": "Auditorium" },
  "學生活動中心": { "zh": "學生活動中心", "en": "Student Activity Center" },
  "工學院二館": { "zh": "工學院二館", "en": "Engineering Building II" },
  "法學院": { "zh": "法學院", "en": "College of Law" },
  "教育學院": { "zh": "教育學院", "en": "College of Education" },
  "教育學院二館": { "zh": "教育學院二館", "en": "Education Building II" },
  "理學院": { "zh": "理學院", "en": "College of Science" },
  "理學院二館": { "zh": "理學院二館", "en": "Science Building II" },
  "中正大學體育館": { "zh": "中正大學體育館", "en": "CCU Gymnasium" },
  "圖書資訊大樓": { "zh": "圖書資訊大樓", "en": "Library and Information Building" },
  "致遠樓": { "zh": "致遠樓", "en": "Zhiyuan Building" },
  "生活商圈": { "zh": "生活商圈", "en": "Living Commercial District" },
  "員工學生福利社": { "zh": "員工學生福利社", "en": "Staff and Student Cooperative" },
  "大學部宿舍E棟": { "zh": "大學部宿舍E棟", "en": "Undergraduate Dormitory E" },
  "大學部宿舍C棟": { "zh": "大學部宿舍C棟", "en": "Undergraduate Dormitory C" },
  "大學部宿舍D棟": { "zh": "大學部宿舍D棟", "en": "Undergraduate Dormitory D" },
  "大學部宿舍B棟": { "zh": "大學部宿舍B棟", "en": "Undergraduate Dormitory B" },
  "大學部宿舍A棟": { "zh": "大學部宿舍A棟", "en": "Undergraduate Dormitory A" },
  "研究生宿舍A棟": { "zh": "研究生宿舍A棟", "en": "Graduate Dormitory A" },
  "研究生宿舍B棟": { "zh": "研究生宿舍B棟", "en": "Graduate Dormitory B" },
  "研究生宿舍E棟": { "zh": "研究生宿舍E棟", "en": "Graduate Dormitory E" },
  "研究生宿舍C棟": { "zh": "研究生宿舍C棟", "en": "Graduate Dormitory C" },
  "研究生宿舍D棟": { "zh": "研究生宿舍D棟", "en": "Graduate Dormitory D" },
  "實習工廠": { "zh": "實習工廠", "en": "Internship Factory" },
  "陶潛": { "zh": "陶潛", "en": "Tao Qian" },
  "鳳凰軒": { "zh": "鳳凰軒", "en": "Fenghuang Pavilion" },
  "創新大樓": { "zh": "創新大樓", "en": "Innovation Building" },
  "現代首席": { "zh": "現代首席", "en": "Modern Chief" },
  "正心學院": { "zh": "正心學院", "en": "Zhengxin Academy" },
  "康乃爾學院": { "zh": "康乃爾學院", "en": "Cornell Academy" },
  "京采": { "zh": "京采", "en": "Jingcai" },
  "墨香苑": { "zh": "墨香苑", "en": "Moxiang Court" },
  "凱格鹿三期": { "zh": "凱格鹿三期", "en": "Kaigelu Phase 3" },
  "集智苑": { "zh": "集智苑", "en": "Jizhi Court" },
  "陶居": { "zh": "陶居", "en": "Tao Ju" },
  "木菊苑": { "zh": "木菊苑", "en": "Muju Court" },
  "書香門第": { "zh": "書香門第", "en": "Shuxiang Mendi" },
  "維多利亞學苑": { "zh": "維多利亞學苑", "en": "Victoria Academy" },
  "哈佛學苑": { "zh": "哈佛學苑", "en": "Harvard Academy" },
  "凱格鹿二期": { "zh": "凱格鹿二期", "en": "Kaigelu Phase 2" },
  "牛津學苑": { "zh": "牛津學苑", "en": "Oxford Academy" },
  "康乃爾學苑": { "zh": "康乃爾學苑", "en": "Cornell Academy" },
  "苗圃": { "zh": "苗圃", "en": "Nursery" },
  "動物實驗室": { "zh": "動物實驗室", "en": "Animal Laboratory" },
  "食凡捲餅": { "zh": "食凡捲餅", "en": "Shi Fan Burrito" },
  "理學院-地震博物館": { "zh": "理學院-地震博物館", "en": "College of Science - Earthquake Museum" },
  "理學院-物理館": { "zh": "理學院-物理館", "en": "College of Science - Physics Building" },
  "金桔學苑": { "zh": "金桔學苑", "en": "Kumquat Academy" },
  "凱格鹿旗艦會館": { "zh": "凱格鹿旗艦會館", "en": "Kaigelu Flagship Hall" },
  "靈糧堂": { "zh": "靈糧堂", "en": "Bread of Life Christian Church" },
  "深白舍": { "zh": "深白舍", "en": "Shenbai House" },
  "橙舍": { "zh": "橙舍", "en": "Orange House" },
  "三豐學苑": { "zh": "三豐學苑", "en": "Sanfeng Academy" },
  "三豐學苑(二期)": { "zh": "三豐學苑(二期)", "en": "Sanfeng Academy (Phase 2)" },
  "柏克萊": { "zh": "柏克萊", "en": "Berkeley" },
  "彬彬": { "zh": "彬彬", "en": "Bin Bin" },
  "夏都": { "zh": "夏都", "en": "Chateau" },
  "管理學院二館": { "zh": "管理學院二館", "en": "Management Building II" },
  "三興村社區活動中心": { "zh": "三興村社區活動中心", "en": "Sanxing Village Community Activity Center" },
  "中正大學環安中心": { "zh": "中正大學環安中心", "en": "CCU Center for Environmental and Occupational Safety and Health" },
  "文學院": { "zh": "文學院", "en": "College of Humanities" },
  "三興國小": { "zh": "三興國小", "en": "Sanxing Elementary School" },
  "納米運動休閒園區": { "zh": "納米運動休閒園區", "en": "Nami Sports and Leisure Park" },
  "中正駕訓班": { "zh": "中正駕訓班", "en": "Zhongzheng Driving School" },
  "登林學苑": { "zh": "登林學苑", "en": "Denglin Academy" },
  "鼎泰": { "zh": "鼎泰", "en": "Dingtai" },
  "紫荊書苑": { "zh": "紫荊書苑", "en": "Bauhinia Academy" },
  "牛筋伯爵": { "zh": "牛筋伯爵", "en": "Count Tendon" },
  "中正大學大門機車停車場": { "zh": "中正大學大門機車停車場", "en": "CCU Main Gate Scooter Parking Lot" },
  "大學部宿舍機車停車場": { "zh": "大學部宿舍機車停車場", "en": "Undergraduate Dormitory Scooter Parking Lot" },
  "匯幸福二期": { "zh": "匯幸福二期", "en": "Hui Xingfu Phase 2" },
  "學生會館": { "zh": "學生會館", "en": "Student Center" },
  "木菊苑二期": { "zh": "木菊苑二期", "en": "Muju Court Phase 2" },
  "天晴": { "zh": "天晴", "en": "Tianqing" },
  "淡如菊": { "zh": "淡如菊", "en": "Danruju" },
  "21金小火鍋": { "zh": "21金小火鍋", "en": "21 Gold Hot Pot" },
  "Just Eat Brunch": { "zh": "Just Eat Brunch", "en": "Just Eat Brunch" },
  "布格早午餐": { "zh": "布格早午餐", "en": "Buger Brunch" },
  "博多屋台拉麵": { "zh": "博多屋台拉麵", "en": "Hakata Yatai Ramen" },
  "夏豔鳳翔會館": { "zh": "夏豔鳳翔會館", "en": "Xiayan Fengxiang Hall" },
  "劍橋世紀": { "zh": "劍橋世紀", "en": "Cambridge Century" },
  "三興村陳厝寮-大樹下簡餐便當": { "zh": "三興村陳厝寮-大樹下簡餐便當", "en": "Sanxing Village Chencuoliao - Dashuxia Fast Food & Bento" },
  "心遠居": { "zh": "心遠居", "en": "Xinyuan Residence" },
  "琪琪健康舖": { "zh": "琪琪健康舖", "en": "Qiqi Health Shop" },
  "阿姨早餐": { "zh": "阿姨早餐", "en": "Auntie's Breakfast" },
  "三興村陳厝寮-轉角早餐店": { "zh": "三興村陳厝寮-轉角早餐店", "en": "Sanxing Village Chencuoliao - Corner Breakfast" },
  "大四喜牛肉麵": { "zh": "大四喜牛肉麵", "en": "Dasixi Beef Noodle Soup" },
  "諾貝爾學院": { "zh": "諾貝爾學院", "en": "Nobel Academy" },
  "常春藤學院": { "zh": "常春藤學院", "en": "Ivy Academy" },
  "凱格鹿九期": { "zh": "凱格鹿九期", "en": "Kaigelu Phase 9" },
  "享住I": { "zh": "享住I", "en": "Xiangzhu I" },
  "凱格鹿八期": { "zh": "凱格鹿八期", "en": "Kaigelu Phase 8" },
  "凱格鹿一期": { "zh": "凱格鹿一期", "en": "Kaigelu Phase 1" },
  "民雄鄉召會二會所(學生中心)": { "zh": "民雄鄉召會二會所(學生中心)", "en": "Minxiong Township Church Meeting Place 2 (Student Center)" },
  "梓園": { "zh": "梓園", "en": "Ziyuan" },
  "歐風學墅": { "zh": "歐風學墅", "en": "European Style Villa" },
  "鵬莊": { "zh": "鵬莊", "en": "Pengzhuang" },
  "米蘭": { "zh": "米蘭", "en": "Milan" },
  "柏睿學院": { "zh": "柏睿學院", "en": "Borui Academy" },
  "康莊": { "zh": "康莊", "en": "Kangzhuang" },
  "菁華學苑": { "zh": "菁華學苑", "en": "Jinghua Academy" },
  "鼎冠學苑": { "zh": "鼎冠學苑", "en": "Dingguan Academy" },
  "唯心之旅": { "zh": "唯心之旅", "en": "Weixin Journey" },
  "三興會館民宿": { "zh": "三興會館民宿", "en": "Sanxing Hall Homestay" },
  "凱媽的家1館": { "zh": "凱媽的家1館", "en": "Kaima's Home Hall 1" },
  "中正會館": { "zh": "中正會館", "en": "Zhongzheng Hall" },
  "蔬香是家": { "zh": "蔬香是家", "en": "Shuxiang Shi Jia" },
  "中正美學": { "zh": "中正美學", "en": "Zhongzheng Aesthetics" },
  "博士學苑": { "zh": "博士學苑", "en": "Ph.D. Academy" },
  "巴豆夭百元美味鍋物": { "zh": "巴豆夭百元美味鍋物", "en": "Ba Dou Yao 100-Yuan Delicious Hot Pot" },
  "光明雅舍": { "zh": "光明雅舍", "en": "Guangming Yashe" },
  "早叄早午餐": { "zh": "早叄早午餐", "en": "Zaosan Brunch" },
  "蔬芙": { "zh": "蔬芙", "en": "Shu Fu" },
  "八方雲集": { "zh": "八方雲集", "en": "Bafang Dumpling" },
  "阿基鍋燒麵": { "zh": "阿基鍋燒麵", "en": "A-Ji Pot Burn Noodles" },
  "光陽機車": { "zh": "光陽機車", "en": "KYMCO" },
  "早餐好樂": { "zh": "早餐好樂", "en": "Breakfast Hao Le" },
  "紘翔車業": { "zh": "紘翔車業", "en": "Hongxiang Motors" },
  "中正大學-廣場公園停車場": { "zh": "中正大學-廣場公園停車場", "en": "CCU - Square Park Parking Lot" },
  "嘉義富野渡假酒店": { "zh": "嘉義富野渡假酒店", "en": "Hoya Resort Hotel Chiayi" },
  "YAMAHA-中正車坊": { "zh": "YAMAHA-中正車坊", "en": "YAMAHA - Zhongzheng Motorcycle Shop" },
  "中正偉文": { "zh": "中正偉文", "en": "Zhongzheng Weiwen" },
  "百田中西式早午餐": { "zh": "百田中西式早午餐", "en": "Baitian Chinese and Western Brunch" },
  "美廉社民雄裕農店": { "zh": "美廉社民雄裕農店", "en": "Simple Mart Minxiong Yunong Store" },
  "明發影印行": { "zh": "明發影印行", "en": "Mingfa Copy Shop" },
  "花圓巧芋": { "zh": "花圓巧芋", "en": "Hua Yuan Qiao Yu" },
  "高點網路學院": { "zh": "高點網路學院", "en": "Knowledge Point E-Learning Academy" },
  "咖啡王國": { "zh": "咖啡王國", "en": "Coffee Kingdom" },
  "小樹苗電腦": { "zh": "小樹苗電腦", "en": "Sapling Computer" },
  "槍與玫瑰": { "zh": "槍與玫瑰", "en": "Guns N' Roses" },
  "橙堡早午餐": { "zh": "橙堡早午餐", "en": "Chengbao Brunch" },
  "韓湯匙 無人拉麵": { "zh": "韓湯匙 無人拉麵", "en": "Han Spoon Unmanned Ramen" },
  "小栗鼠cafe": { "zh": "小栗鼠cafe", "en": "Chipmunk Cafe" },
  "溫家冷滷味": { "zh": "溫家冷滷味", "en": "Wen's Cold Luwei" },
  "月亮與貓｜貓貓甜點店": { "zh": "月亮與貓｜貓貓甜點店", "en": "Moon and Cat | Cat Dessert Shop" },
  "茶湯會 民雄神農店": { "zh": "茶湯會 民雄神農店", "en": "TP TEA Minxiong Shennong Store" },
  "豪緯麵食館": { "zh": "豪緯麵食館", "en": "Haowei Noodle Restaurant" },
  "仙草奶酪": { "zh": "仙草奶酪", "en": "Grass Jelly Panna Cotta" },
  "古早味炒麵（脆皮臭豆腐）": { "zh": "古早味炒麵（脆皮臭豆腐）", "en": "Traditional Fried Noodles (Crispy Stinky Tofu)" },
  "鍋序": { "zh": "鍋序", "en": "Guoxu Hot Pot" },
  "蘭姐手工水餃": { "zh": "蘭姐手工水餃", "en": "Sister Lan's Handmade Dumplings" },
  "紅樓極麵": { "zh": "紅樓極麵", "en": "Red Mansion Extreme Noodles" },
  "東方美早午餐": { "zh": "東方美早午餐", "en": "Dongfangmei Brunch" },
  "隱客廳": { "zh": "隱客廳", "en": "Hidden Living Room" },
  "一番食堂": { "zh": "一番食堂", "en": "Ichiban Eatery" },
  "洵香麻辣燙": { "zh": "洵香麻辣燙", "en": "Xunxiang Malatang" },
  "翅炸鍋": { "zh": "翅炸鍋", "en": "Wing Fried Pot" },
  "富成屋拉麵": { "zh": "富成屋拉麵", "en": "Fuchengu Ramen" },
  "豐正食堂": { "zh": "豐正食堂", "en": "Fengzheng Eatery" },
  "傻師傅神農店": { "zh": "傻師傅神農店", "en": "Dumb Master Shennong Store" },
  "烘培工房": { "zh": "烘培工房", "en": "Baking Workshop" },
  "嘉農小館": { "zh": "嘉農小館", "en": "Jianong Eatery" },
  "榕樹下": { "zh": "榕樹下", "en": "Under the Banyan Tree" },
  "中正海南雞飯": { "zh": "中正海南雞飯", "en": "Zhongzheng Hainanese Chicken Rice" },
  "鹿初Brunch": { "zh": "鹿初Brunch", "en": "Luchu Brunch" },
  "洪媽媽泰式簡餐": { "zh": "洪媽媽泰式簡餐", "en": "Mother Hong's Thai Fast Food" },
  "有go滷乾式炒滷味": { "zh": "有go滷乾式炒滷味", "en": "You Go Lu Dry Stir-fried Luwei" },
  "王仔滷味": { "zh": "王仔滷味", "en": "Wangzai Luwei" },
  "愛恨椒雞": { "zh": "愛恨椒雞", "en": "Love and Hate Pepper Chicken" },
  "鹽酥雞中正雞場": { "zh": "鹽酥雞中正雞場", "en": "Zhongzheng Salted Crispy Chicken Farm" },
  "清火堂 冰品·甜湯": { "zh": "清火堂 冰品·甜湯", "en": "Qinghuotang Ice and Sweet Soup" },
  "農閒時刻的粥": { "zh": "農閒時刻的粥", "en": "Congee of Leisure Time" },
  "十畝田滷味": { "zh": "十畝田滷味", "en": "Shimutian Luwei" },
  "巧味果汁": { "zh": "巧味果汁", "en": "Qiaowei Juice" },
  "阿湯哥脆皮湯包": { "zh": "阿湯哥脆皮湯包", "en": "Tom's Crispy Soup Dumplings" },
  "七里香": { "zh": "七里香", "en": "Qilixiang" },
  "早安山丘": { "zh": "早安山丘", "en": "Morning Hill" },
  "大榮數位輸出影印行": { "zh": "大榮數位輸出影印行", "en": "Darong Digital Print & Copy" },
  "渝香园簡餐": { "zh": "渝香园簡餐", "en": "Yuxiangyuan Fast Food" },
  "鴻昇數位輸出影印中心": { "zh": "鴻昇數位輸出影印中心", "en": "Hongsheng Digital Print & Copy Center" },
  "Nice Nine 雙醬咖哩": { "zh": "Nice Nine 雙醬咖哩", "en": "Nice Nine Dual Sauce Curry" },
  "豪豪吃早餐": { "zh": "豪豪吃早餐", "en": "Hao Hao Eat Breakfast" },
  "關東煮炒麵炒米粉": { "zh": "關東煮炒麵炒米粉", "en": "Oden, Fried Noodles & Fried Rice Noodles" },
  "越式炒泡麵、河粉": { "zh": "越式炒泡麵、河粉", "en": "Vietnamese Fried Instant Noodles & Pho" },
  "豪記滷味-神農路": { "zh": "豪記滷味-神農路", "en": "Haoji Luwei - Shennong Road" },
  "中正大學員工子女非營利幼兒園": { "zh": "中正大學員工子女非營利幼兒園", "en": "CCU Employee Children Non-Profit Kindergarten" },
  "東側門汽機車停車場": { "zh": "東側門汽機車停車場", "en": "East Gate Car and Scooter Parking Lot" },
  "全家便利商店-學人宿舍店": { "zh": "全家便利商店-學人宿舍店", "en": "FamilyMart - Scholar Dormitory Store" },
  "管理學院": { "zh": "管理學院", "en": "College of Management" },
  "中正大學訪客停車場": { "zh": "中正大學訪客停車場", "en": "CCU Visitor Parking Lot" },
  "中正大學公車站": { "zh": "中正大學公車站", "en": "CCU Bus Station" },
  "麗文-中正大學店": { "zh": "麗文-中正大學店", "en": "Liwen Campus Bookstore - CCU Store" },
  "露易莎-中正大學店": { "zh": "露易莎-中正大學店", "en": "Louisa Coffee - CCU Store" },
  "學生餐廳": { "zh": "學生餐廳", "en": "Student Cafeteria" },
  "中正大學郵局": { "zh": "中正大學郵局", "en": "CCU Post Office" },
  "中正大學影印店": { "zh": "中正大學影印店", "en": "CCU Copy Shop" },
  "中正大學網球場": { "zh": "中正大學網球場", "en": "CCU Tennis Court" },
  "中正大學田徑場": { "zh": "中正大學田徑場", "en": "CCU Track and Field" },
  "中正大學籃球場": { "zh": "中正大學籃球場", "en": "CCU Basketball Court" },
  "中正大學排球場": { "zh": "中正大學排球場", "en": "CCU Volleyball Court" },
  "中正大學棒球場": { "zh": "中正大學棒球場", "en": "CCU Baseball Field" },
  "中正大學景觀花園": { "zh": "中正大學景觀花園", "en": "CCU Landscape Garden" },
  "中正大學射箭場": { "zh": "中正大學射箭場", "en": "CCU Archery Range" },
  "中正大學壘球場": { "zh": "中正大學壘球場", "en": "CCU Softball Field" },
  "中正大學足球場": { "zh": "中正大學足球場", "en": "CCU Football Field" },
  "中正大學高爾夫球練習場": { "zh": "中正大學高爾夫球練習場", "en": "CCU Golf Practice Range" },
  "中正大學室外游泳池": { "zh": "中正大學室外游泳池", "en": "CCU Outdoor Swimming Pool" },
  "研究生機車停車場": { "zh": "研究生機車停車場", "en": "Graduate Student Scooter Parking Lot" },
  "中正大學室內綜合球場": { "zh": "中正大學室內綜合球場", "en": "CCU Indoor Sports Arena" },
  "中正大學攀岩場": { "zh": "中正大學攀岩場", "en": "CCU Rock Climbing Wall" },
  "中正大學室內游泳池": { "zh": "中正大學室內游泳池", "en": "CCU Indoor Swimming Pool" },
  "意素家": { "zh": "意素家", "en": "Yi Su Jia Vegetarian" },
  "旺記": { "zh": "旺記", "en": "Wangji" },
  "吳家紅茶冰": { "zh": "吳家紅茶冰", "en": "Wu's Black Tea Ice" },
  "海派鹽酥雞": { "zh": "海派鹽酥雞", "en": "Haipai Salted Crispy Chicken" },
  "楊家豆漿": { "zh": "楊家豆漿", "en": "Yang's Soybean Milk" },
  "御清江餐坊": { "zh": "御清江餐坊", "en": "Yuqingjiang Restaurant" },
  "Chill Bowl笑杯": { "zh": "Chill Bowl笑杯", "en": "Chill Bowl" },
  "不吃不可鹽水雞": { "zh": "不吃不可鹽水雞", "en": "Must Eat Salted Water Chicken" },
  "德州撲克競技協會": { "zh": "德州撲克競技協會", "en": "Texas Hold'em Poker Association" },
  "粥鮮廣東粥": { "zh": "粥鮮廣東粥", "en": "Zhouxian Cantonese Congee" },
  "和義日式料理": { "zh": "和義日式料理", "en": "Heyi Japanese Cuisine" },
  "墨醬章魚燒": { "zh": "墨醬章魚燒", "en": "Mojiang Takoyaki" },
  "鮮盛食堂": { "zh": "鮮盛食堂", "en": "Xiansheng Eatery" },
  "頭家麵線": { "zh": "頭家麵線", "en": "Toujia Vermicelli" },
  "6833自助桌遊": { "zh": "6833自助桌遊", "en": "6833 Self-Service Board Games" },
  "魯都香滷味": { "zh": "魯都香滷味", "en": "Ludouxiang Luwei" },
  "果真 現打真果汁": { "zh": "果真 現打真果汁", "en": "Guozhen Fresh Juice" },
  "西貢小吃店": { "zh": "西貢小吃店", "en": "Saigon Snack Shop" },
  "綺飛時尚髮藝社": { "zh": "綺飛時尚髮藝社", "en": "Qifei Fashion Hair Salon" },
  "麻舍": { "zh": "麻舍", "en": "Mashe" },
  "重症電癮院": { "zh": "重症電癮院", "en": "Zhongzheng Dian Yin Yuan" },
  "愛麻50KTV桌遊館": { "zh": "愛麻50KTV桌遊館", "en": "Ai Ma 50 KTV & Board Game House" }
};